#!/usr/bin/env node

import fs from "node:fs";
import { consola } from "consola";
import meow from "meow";


// CLI
// e.g. kelp <command> <options>

const cli = meow(`
  Usage
    $ kelp <command> <options>
  
  Commands
    route <path> Generate a template route.
    init         Initialize a new Kelp project.
`, {
  importMeta: import.meta,
  flags: {
    help: {
      type: "boolean",
      shortFlag: "h",
    },
  },
});

// Commands
// e.g. kelp generate <options>

const [command, ...args] = cli.input;

switch (command) {
  case "route": {
    if (args.length === 0) {
      consola.error("Please specify a route name.");
      break;
    }
    const routeName = args[0];
    const routePath = `./routes/${routeName}.js`;
    if (!fs.existsSync("./routes")) {
      fs.mkdirSync("./routes");
    }
    if (fs.existsSync(routePath)) {
      consola.error("Route already exists.");
      break;
    }
    fs.writeFileSync(routePath, `// Generated by Kelp CLI
export default {
  method: "GET",
  path: "/${routeName}",
  // You can customize the handler to your liking.
  handler: async (req, res) => {
    res.send("Hello World!");
  }
}`);

    consola.success(`Route ${routeName} created.`);

    break;
  }
  case "init": {
    // Create a new Kelp project.

    // Check if index.js exists.
    if (fs.existsSync("./index.js")) {
      consola.error("Kelp project already exists.");
      break;
    }
    fs.writeFileSync("./index.js", `// Generated by Kelp CLI
import express from "express";
import kelpify from "@znci/kelp";

const app = express();
kelpify(app, {
  // options go here! See the README for more info.
});
`);

    // Create a routes folder.
    fs.mkdirSync("./routes");

    // Create a default route.
    fs.writeFileSync("./routes/index.js", `// Generated by Kelp CLI
export default {
  method: "GET",
  path: "/",
  handler: async (req, res) => {
    res.send("Hello World!");
  }
}
`);

    // Create a default package.json.
    fs.writeFileSync("./package.json", `{
  "name": "kelp-project",
  "version": "0.0.1",
  "description": "A Kelp project.",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "Kelp CLI",
  "license": "MIT",
  "dependencies": {
    "@znci/kelp": "^0.0.1",
    "express": "^4.17.1"
  }
}
`);

    consola.success("Kelp project created! Run `npm install` to install dependencies.");
    break;

  }
  default: {
    cli.showHelp();
    break;
  }

}


process.exit(0);
